sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anfelo/react-test -f ./app/Dockerfile.dev ./app

script:
  - docker run -e CI=true anfelo/react-test npm run test

after_sucess:
  - docker build -t anfelo/multi-client ./app
  - docker build -t anfelo/multi-nginx ./nginx
  - docker build -t anfelo/multi-server ./server
  - docker build -t anfelo/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the build images and push those to docker hub
  - docker push anfelo/multi-client
  - docker push anfelo/multi-nginx
  - docker push anfelo/multi-server
  - docker push anfelo/multi-worker
