sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anfelo/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true anfelo/react-test npm run test

after_sucess:
  - docker build -t anfelo/multi-client -f ./client
  - docker build -t anfelo/multi-nginx -f ./nginx
  - docker build -t anfelo/multi-server -f ./server
  - docker build -t anfelo/multi-worker -f ./worker